name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: docker/setup-buildx-action@v2

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          fail-on-cache-miss: false
          restore-keys: |
            docker-cache-${{ github.ref_name }}-${{ vars.GITHUB_SHA }}
            docker-cache-${{ github.ref_name }}-
            docker-cache-

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          cache-from: type=local,dest=/tmp/docker-cache
          cache-to: type=local,dest=/tmp/docker-cache-new

      - name: Update Cache
        run:
          mv /tmp/docker-cache-new /tmp/docker-cache
